import type { ConfigData } from './config-data.js'

export default {
  rules: {
    'function-max-lines': { max: 60 },
    'function-max-complexity': { max: 10 },
    'function-max-params': { max: 4 },
    'function-max-nesting': { max: 4 },
    'class-max-lines': { max: 500 },
    'class-max-methods': { max: 20 },
    'max-file-lines': { max: 300 },
    'naming-convention': { style: 'camelCase' },
    'no-duplicate-imports': {},
    'no-magic-numbers': { ignore: '0,1,-1' },
    'declaration-order': { order: ['import', '*', 'export'] },
  },
  ignore: [
    '.git',
    'vendor',
    'node_modules',
    'dist',
    '.next',
    '.nuxt',
    'coverage',
    '*.min.js',
    '*.min.jsx',
    '*.min.ts',
    '*.min.tsx',
    '__pycache__',
    '.venv',
    'venv',
    'env',
    '.tox',
    '.mypy_cache',
    '*.pyc',
    'build',
    'out',
    'target',
    '.gradle',
    '.idea',
  ],
} as ConfigData
